// jspp/dispatch-pattern/vue-3/src/components/TodoList/Form.vue
<script setup>
  import { ref } from 'vue';

  const todoText = ref('');

  const emit = defineEmits(['addTodo']);

  const addTodo = () => {
    if (!todoText.value.length) {
      return;
    }

    emit('addTodo', {
      id: new Date().getTime(),
      content: todoText.value,
      completed: false
    })
  }
</script>

<template>
  <div>
    <input 
      type="text"
      placeholder="Please input someThing..."
      v-model="todoText"
    />
    <button
      @click="addTodo"
    >ADD</button>
  </div>
</template>

<style lang="scss" scoped>

</style>

// jspp/dispatch-pattern/react-1/src/components/TodoList/Form.jsx
const { useState } = React;

function Form ({ addTodo }) {

  const [ todoText, setTodoText ] = useState('');

  const onAddTodo = () => {
    if (!todoText.length) {
      return;
    }

    addTodo({
      id: new Date().getTime(),
      content: todoText,
      completed: false
    });

    setTodoText('');
  }

  return (
    <div>
      <input 
        type="text" 
        value={ todoText }
        onChange={ (e) => setTodoText(e.target.value) }
        placeholder="Please input something..."
      />
      <button
        onClick={ onAddTodo }
      >ADD</button>
    </div>
  );
}

export default Form;
