// jspp/dispatch-pattern/vue-3/src/components/TodoList/index.vue
<script setup>
  import FormComp from './Form';
  import ListComp from './List';
  import { provide } from 'vue';

  import {
    todoReducer,
    ADD_TODO,
    TOGGLE_TODO,
    REMOVE_TODO
  } from './store';

  const {
    todoList,
    addCount,
    removeCount, 
    todoDispatch
  } = todoReducer();

  provide('todoHandlers', {
    toggleTodo: todoDispatch(TOGGLE_TODO),
    removeTodo: todoDispatch(REMOVE_TODO)
  });

  const addTodo = todoDispatch(ADD_TODO);

</script>

<template>
  <div>
    <form-comp
      @add-todo="addTodo"
    ></form-comp>
    <list-comp
      :todo-list="todoList"
      :add-count="addCount"
      :remove-count="removeCount"
    ></list-comp>
  </div>
</template>

<style lang="scss" scoped>

</style>

// jspp/dispatch-pattern/react-1/src/components/TodoList/index.jsx
import FormComp from './Form';
import ListComp from './List';

const { useState, createContext } = React;
export const ListContext = createContext({});

function TodoList () {

  const [ addCount, setAddCount ] = useState(0);
  const [ removeCount, setRemoveCount ] = useState(0);
  const [ todoList, setTodoList ] = useState([]);

  const onAddTodo = (todo) => {
    setTodoList(todoList => [ ...todoList, todo ]);
    setAddCount(addCount + 1);
  }

  const onToggleTodo = (id) => {
    setTodoList(todoList => {
      return todoList.map(item => {
        item.id === id && (item.completed = !item.completed);
        return item;
      })
    })
  }

  const onRemoveTodo = (id) => {
    setTodoList(todoList => 
      todoList.filter(item => item.id !== id)
    );
    setRemoveCount(removeCount + 1);
  }

  return (
    <div>
      <FormComp
        addTodo={ onAddTodo }
      ></FormComp>
      <ListContext.Provider value={{
        toggleTodo: onToggleTodo,
        removeTodo: onRemoveTodo
      }}>
        <ListComp
          addCount={ addCount }
          removeCount={ removeCount }
          todoList={ todoList }
        ></ListComp>
      </ListContext.Provider>
    </div>
  );
}

export default TodoList;
