// jspp/dispatch-pattern/vue-3/src/components/TodoList/ListItem.vue
<script setup>
  import { inject } from 'vue';

  const {
    toggleTodo,
    removeTodo
  } = inject('todoHandlers');

  const props = defineProps({
    data: {
      type: Object,
      default: () => ({})
    }
  })
</script>

<template>
  <li>
    <input 
      type="checkbox"
      :checked="data.completed"
      @change="toggleTodo(data.id)"
    />
    <span
      :style="{
        textDecoration: data.completed ? 'line-through' : ''
      }"
    >{{ data.content }}</span>
    <button
      @click="removeTodo(data.id)"
    >REMOVE</button>
  </li>
</template>

<style lang="scss" scoped>

</style>

// jspp/dispatch-pattern/react-2/src/components/TodoList/ListItem.jsx
import { ListContext } from '.';
import { REMOVE_TODO, TOGGLE_TODO } from './store';
const { useContext } = React;

function ListItem ({ data }) {
  const { dispatch } = useContext(ListContext);

  return (
    <li>
      <input 
        type="checkbox" 
        checked={ data.completed } 
        onChange={ () => dispatch({
          type: TOGGLE_TODO,
          payload: data.id
        }) }
      />
      <span
        style={{
          textDecoration: data.completed ? 'line-through' : ''
        }}
      >{ data.content }</span>
      <button
        onClick={ () => dispatch({
          type: REMOVE_TODO,
          payload: data.id
        }) }
      >REMOVE</button>
    </li>
  );
}

export default ListItem;

/**
 * {
 *   id: number,
 *   content: string,
 *   completed: boolean
 * }
 * 
 * 
 */
