// jspp/dispatch-pattern/vue-3/src/components/TodoList/List.vue
<script setup>
  import ListItem from './ListItem';

  const props = defineProps({
    todoList: {
      type: Array,
      default: () => []
    },
    addCount: {
      type: Number,
      default: 0
    },
    removeCount: {
      type: Number,
      default: 0
    }
  })
</script>

<template>
  <div>
    <p>
      <span>已添加过{{ addCount }}条</span> / 
      <span>已删除过{{ removeCount }}条</span>
    </p>
    <ul>
      <list-item
        v-for="todo of todoList"
        :key="todo.id"
        :data="todo"
      ></list-item>
    </ul>
  </div>
</template>

<style lang="scss" scoped>

</style>

// jspp/dispatch-pattern/react-2/src/components/TodoList/List.jsx
import ListItem from './ListItem';

function List ({ todoList, addCount, removeCount }) {
  return (
    <div>
      <p>
        <span>已添加过{ addCount }条</span> /
        <span>已删除过{ removeCount }条</span>
      </p>
      <ul>
        {
          todoList.map(item => (
            <ListItem
              data={ item }
              key={ item.id }
            ></ListItem>
          ))
        }
      </ul>
    </div>
  );
}

export default List;
